package com.zzb.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zzb.greendaodemo.db.WorkLogBean;

import com.zzb.greendaodemo.db.WorkLogBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workLogBeanDaoConfig;

    private final WorkLogBeanDao workLogBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workLogBeanDaoConfig = daoConfigMap.get(WorkLogBeanDao.class).clone();
        workLogBeanDaoConfig.initIdentityScope(type);

        workLogBeanDao = new WorkLogBeanDao(workLogBeanDaoConfig, this);

        registerDao(WorkLogBean.class, workLogBeanDao);
    }
    
    public void clear() {
        workLogBeanDaoConfig.clearIdentityScope();
    }

    public WorkLogBeanDao getWorkLogBeanDao() {
        return workLogBeanDao;
    }

}
